name: Publish release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  publish-release:
    uses: refinedmods/refinedarchitect/.github/workflows/publish-release.yml@v0.19.1
    secrets: inherit
    with:
      project-name: 'Refined Storage - Quartz Accessories'
      announce: true
      mutation-testing: false
      sonarqube: true